# -*- coding: utf-8 -*-
from litefac.utilities import _


STANDARD_RECEIPT_TEMPLATE_ID = 1
EXTRA_RECEIPT_TEMPLATE_ID = 2
DEFAULT_PRODUCT_TYPE_NAME = _(u"默认加工件")
DEFAULT_PRODUCT_NAME = _(u"默认加工件")
DEFAULT_TECH_REQ = _(u"默认")

ITEMS_PER_PAGE = 15
UNLOAD_SESSION_PER_PAGE = 15
STORE_BILL_PER_PAGE = 15
DELIVERY_SESSION_PER_PAGE = 15
ORDER_PER_PAGE = 15

# order types

STANDARD_ORDER_TYPE = 1
EXTRA_ORDER_TYPE = 2

EXTRA_ORDER_TYPE_NAME = u"计件"
STANDARD_ORDER_TYPE_NAME = u"计重"

ADMIN_USER_ID = 1

PRINT_COUNT_PER_PAGE = u"print_count_per_page"
